CREATE TABLE users (id INT NOT NULL, email VARCHAR(255), name VARCHAR(255));
ALTER TABLE users ADD INDEX z_email_idx (email), ALGORITHM=INPLACE, LOCK=NONE;
ALTER TABLE users ADD COLUMN middle_col INT;
ALTER TABLE users ADD INDEX a_name_idx (name), ALGORITHM=COPY, LOCK=SHARED;
