-params none keeps parameters as written, so it cannot serve a statement whose
parameters sqlgg has to generate:

  $ sqlgg -no-header -params none -gen xml - <<'EOF'
  > CREATE TABLE t (id INT NOT NULL, name TEXT NOT NULL);
  > -- @add
  > INSERT INTO t VALUES;
  > EOF
  Cannot use `-params none` with autogenerated parameters
  Errors encountered, no code generated
  [1]

Written parameters are fine:

  $ sqlgg -no-header -params none -gen xml - <<'EOF'
  > CREATE TABLE t (id INT NOT NULL, name TEXT NOT NULL);
  > -- @add
  > INSERT INTO t (id, name) VALUES (@id, @name);
  > EOF
  <?xml version="1.0"?>
  
  <sqlgg>
   <stmt name="create_t" sql="CREATE TABLE t (id INT NOT NULL, name TEXT NOT NULL)" category="DDL" kind="create" target="t" cardinality="0">
    <in/>
    <out/>
   </stmt>
   <stmt name="add" sql="INSERT INTO t (id, name) VALUES (@id, @name)" category="DML" kind="insert" target="t" cardinality="0">
    <in>
     <value name="id" type="Int"/>
     <value name="name" type="Text"/>
    </in>
    <out/>
   </stmt>
   <table name="t">
    <schema>
     <value name="id" type="Int"/>
     <value name="name" type="Text"/>
    </schema>
   </table>
  </sqlgg>
