(executable
  (public_name sqlgg)
  (package sqlgg)
  (name cli)
  (promote (until-clean))
  (libraries
    dune-build-info
    extlib
    oUnit
    sqlgg
    sqlgg_ir
    unix
    yojson
  )
  (flags (:standard -open Sqlgg_ir))
  (preprocess (pps ppx_deriving.std))
)

(rule
 (alias runtest)
 (deps ./cli.exe)
 (action
   (run ./cli.exe -test)))

(rule
 (targets _cli-options.md)
 (deps ./cli.exe)
 (mode (promote (into ../doc)))
 (action
   (with-stdout-to %{targets} (run ./cli.exe -options-md))))
