(executable
  (public_name sqlgg)
  (package sqlgg)
  (modules :standard \ sqlgg_ir)
  (name cli)
  (promote (until-clean))
  (libraries
    extlib
    oUnit
    sqlgg
    unix
  )
  (preprocess (pps ppx_deriving.std))
)

(executable
  (public_name sqlgg-ir)
  (package sqlgg)
  (modules sqlgg_ir)
  (name sqlgg_ir)
  (libraries sqlgg yojson)
)

(rule
 (alias runtest)
 (deps ./cli.exe)
 (action
   (run ./cli.exe -test)))

(rule
 (targets _cli-options.md)
 (deps ./cli.exe)
 (mode (promote (into ../doc)))
 (action
   (with-stdout-to %{targets} (run ./cli.exe -options-md))))

(rule
 (alias runtest)
 (targets sqlgg-ir.schema.json)
 (deps ./sqlgg_ir.exe)
 (mode (promote (into ../schema)))
 (action
   (with-stdout-to %{targets} (run ./sqlgg_ir.exe --json-schema))))
