(* Code generation *)

open Printf
open ExtLib
open Sqlgg
open Prelude

let params_mode : Sql_template.placeholder option ref = ref None

let name_of attr index =
  match attr.Sql.name with
  | "" -> sprintf "_%u" index
  | s -> s

let make_param_name index (p : Sql.param_id) =
  match p.value with
  | None -> sprintf "_%u" index
  | Some s -> s

let show_param_name (p : Sql.Type.t Sql.param) index = make_param_name index p.id

let default_name str index = sprintf "%s_%u" str index

let is_param_nullable (param : Sql.Type.t Sql.param) = Sql.Type.is_nullable param.typ
let is_attr_nullable (attr : Sql.attr) = Sql.Type.is_nullable attr.domain

type value = { vname : string; vtyp : string; nullable : bool }

module type LangTypes = sig
  val as_api_type : Sql.Type.t -> string
  val as_lang_type : Sql.Type.t -> string
end

let rec find_param_ids l =
  List.concat_map
    (function
      | Sql.Single (p, _) | SingleIn (p, _) -> [ p.id ]
      | Choice (id, _) -> [ id ]
      | OptionActionChoice (id, _, _, _) -> [ id ]
      | ChoiceIn { param; vars; _ } -> find_param_ids vars @ [ param ]
      | SharedVarsGroup (vars, _) -> find_param_ids vars
      | TupleList (id, _) -> [ id ]
      | DynamicSelect (id, _) -> [ id ]
      | DynamicSelectJoin _ -> [])
    l

let names_of_vars l =
  find_param_ids l |> List.mapi make_param_name |> List.unique ~cmp:String.equal

let rec params_only l =
  List.concat_map
    (function
      | Sql.Single (p, _) -> [ p ]
      | OptionActionChoice _ | Choice _ -> fail "dynamic choices not supported for this host language"
      | DynamicSelect _ -> fail "dynamic selects not supported for this host language (params_only)"
      | v -> params_only (Sql.sub_vars v))
    l

let rec inparams_only l =
  List.concat_map
    (function
      | Sql.SingleIn (p, _) -> [ p ]
      | ChoiceIn { vars; _ } -> inparams_only vars
      | _ -> [])
    l

module Translate (T : LangTypes) = struct
  let show_param_type p = T.as_api_type p.Sql.typ

  let schema_to_values list =
    List.mapi
      (fun i attr ->
        {
          vname = name_of attr i;
          vtyp = T.as_lang_type attr.Sql.domain;
          nullable = is_attr_nullable attr;
        })
      list

  let all_params_to_values l =
    l
    |> List.mapi (fun i p ->
           {
             vname = show_param_name p i;
             vtyp = T.as_lang_type p.typ;
             nullable = is_param_nullable p;
           })
    |> List.unique ~cmp:(fun v1 v2 -> String.equal v1.vname v2.vname)
end

let (inc_indent,dec_indent,make_indent) =
  let v = ref 0 in
  (fun () -> v := !v + 2),
  (fun () -> v := !v - 2),
  (fun () -> String.make !v ' ')

let print_indent () = print_string (make_indent ())
let indent s = print_indent (); print_string s
let indent_endline s = print_indent (); print_endline @@ String.trim s
let output fmt = ksprintf indent_endline fmt
let output_l = List.iter indent_endline
let print fmt = ksprintf print_endline fmt
let indented k = inc_indent (); k (); dec_indent ()

let spell index ({ param; original } : Sql_template.bind) =
  match !params_mode with
  | None -> original
  | Some Named -> "@" ^ show_param_name param index
  | Some Unnamed -> "?"
  | Some Oracle -> ":" ^ show_param_name param index
  | Some PostgreSQL -> "$" ^ string_of_int (index + 1)

let get_sql (q : Query.named) = Sql_template.fill ~spell q.template

let get_sql_string_only stmt =
  match get_sql stmt with
  | [ `Text s ] -> s
  | _ -> fail "dynamic choices not supported for this language"

let time_string () =
  let module U = Unix in
  let t = U.time () |> U.gmtime in
  sprintf "%04u-%02u-%02uT%02u:%02uZ" (1900 + t.U.tm_year) (t.U.tm_mon+1) t.U.tm_mday t.U.tm_hour t.U.tm_min

module type Generator = sig
  type t
  val generate : t -> string -> Query.named list -> unit
  val start : unit -> t
  val comment : t -> ('a,unit,string,unit) format4 -> 'a
  val empty_line : t -> unit
end

module Make(S : Generator) = struct

let generate_header out mode =
  S.comment out "DO NOT EDIT MANUALLY";
  S.comment out "";
  let suffix =
    match mode with
    | `Full -> sprintf " %s on %s" Sqlgg_config.version (time_string ())
    | `Without_timestamp -> sprintf " %s" Sqlgg_config.version
    | `Static -> ""
  in
  S.comment out "generated by sqlgg%s" suffix;
  S.empty_line out

let process name stmts =
  let out = S.start () in
  Option.may (generate_header out) !Sqlgg_config.gen_header;
  S.generate out name stmts

end
